---

- include: install.yml
  tags:
    - manala_grafana

- include: config.yml
  tags:
    - manala_grafana

- include: services.yml
  tags:
    - manala_grafana
    - manala.services

- include: datasources.yml
  tags:
    - manala_grafana

- include: dashboards.yml
  tags:
    - manala_grafana
